### ISSUE TITLE
Support for expanding "..." 

### ISSUE THREAD

**Issue by shujaatak** [rochus-keller/EbnfStudio#3]
Let suppose one write the following:

```
letter ::= 'A' ... 'Z' | 'a' ... 'z'
```
then some feature for expanding it automatically in EbnfStudio would be so awesome!

**Example:**

```
digit ::= '0' ... '9'
```
expanded to:

```
digit ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
```

**Comment by rochus-keller** [comment]
That looks like a typical lexer production. EbnfStudio is only a parser generator tool, useful for LL(1) grammars with LL(k) exceptions.
